### ISSUE TITLE
405 Client Error : METHOD NOT ALLOWED error

### ISSUE THREAD

**Issue by 1000000000000000000000000000000** [neolei/DSSPparser#4]
![image](https://user-images.githubusercontent.com/81730040/190285371-6d53e9ba-dcb5-4863-a354-e2d5212a88c2.png)

The error above is what I get when I am trying to run your example code. specifically the following example code:

from DSSPparser import pdbToxssp
result = pdbToxssp("2GW9")

I believe this has something to do with the xssp-api wrapper tool you are using. I think they are having problems but there might be some patches you might be able to try to resolve this issue. Currenlyt, there doesn't seem to be a good solution to convert a PDB file to a DSSP file automatically.

Thanks for the help in advance!

**Comment by wangleiofficial** [comment]
Thanks, i fixed the dssp function.
```
Note: please install the DSSP software.
conda install -c salilab dssp
```
```
from DSSPparser import pdbToxssp_local
result = pdbToxssp("2GW9")
```
